apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-mega-project:1.0.0-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-mega-project:1.0.0-16
  template:
    metadata:
      labels:
        app: devops-mega-project:1.0.0-16
    spec:
      containers:
        - name: devops-mega-project:1.0.0-16
          image: mydevopsuser46/devops_mega_project:1.0.0-17
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
